import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
    containerL:{
        flexDirection:'row',
        backgroundColor:'white',
        width:'95%',
        borderTopLeftRadius:50,
        borderBottomLeftRadius:50,
        borderWidth:0.5,
        borderColor:'#E6E6E6',
        borderTopRightRadius:20,
        borderBottomRightRadius:20,
        marginVertical:5,
        alignSelf:'center',
        justifyContent:'space-between',
        alignItems:'center'
    },
    header:{
        height:80,
        backgroundColor:'white',
        borderBottomWidth:0.5,
        borderBottomColor:'#E6E6E6',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    ImgT:{
        width:80,
        height:80,
        borderRadius:100,
    },
    title:{
        fontSize:25,
        fontWeight:'bold',
        color:'black',
        marginLeft:15
    },
    btout:{
        width:70,
        height:30,
        backgroundColor:'orange',
        justifyContent:'center',
        alignItems:'center',
        borderRadius:12,
        marginRight:10
    },
    outtxt:{
        color:'white',
        fontWeight:'bold'
    },
    containerLeft:{
        flexDirection:'row',
        alignItems:'center',
    },
    ContainerImg:{
        width:80,
        height:80,
        justifyContent:'flex-end',
    },
    in4:{
        marginLeft:10
    },
    onlineSt:{
        backgroundColor:'#01DF3A',
        width:22,
        height:22,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:10,
        alignSelf:'flex-end',
        marginRight:5,
        borderColor:'white',
        borderWidth:2,
    },
    offlineSt:{
        backgroundColor:'#FF8000',
        width:22,
        height:22,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:10,
        alignSelf:'flex-end',
        marginRight:5,
        borderColor:'white',
        borderWidth:2,
    },
    Img:{
        width:80,
        height:80,
        borderRadius:100,
        position: 'absolute',
    },
    IconCall:{
        width:50,
        height:50,
        marginRight:10
    },
    center:{
        justifyContent:'center',
        marginLeft:10
    },
    nameTS:{
        fontWeight:'bold',
        fontSize:17,
        color:'grey',
    },
    mailTS:{
        fontSize:14,
        color:'grey',
    },
    list:{
        height:'89%'
    },
})
export default styles
